### ISSUE TITLE
USER STORY: Product details

### ISSUE THREAD

**Issue by Godinhoweverson** [Godinhoweverson/dbz-eiche-ecommerce#4]
As a **user**, I want to view **product details**.

Acceptance criteria

- Clicking on a product from the main page should lead to a dedicated product details page.
- The product details page should prominently display the product image name, and price.

**Task:**

- [x] Set up HTML structure for the product details page.

- [x] Use Bootstrap to create a responsive layout for different screen sizes.

- [x] Use CSS to added style to the page.

- [x] Display Product Information:

1. Display the product Image, name and price prominently on the details page.

- [x]  Ensure the design is responsive across various devices.
